apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongodb
  name: mongodb
spec:
  ports:
    - port: 27017
  selector:
    app: mongodb
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: harbor.pcf.sx/matt/mongo:v1
        ports:
        - containerPort: 27017
        env:
        - name: MONGODB_ADMIN_PASSWORD
          value: pivotal123
        - name: MONGODB_USER
          value: pivotal
        - name: MONGODB_DATABASE
          value: pivotal
        - name: MONGODB_PASSWORD
          value: pivotal123
        - name: MONGODB_PASS
          value: pivotal123

